backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
public_folder: '/_astro'

collections:
  - name: 'post'
    label: 'Post'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      #- { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: true,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'string' }
      - { label: 'Datum (start)', name: 'publishDate', widget: 'datetime', required: true }
      - { label: 'Slutdatum', name: 'endDate', widget: 'datetime', required: false, hint: 'Behövs ej' }
      #- { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Vidare information fritext'}
      - { label: 'Location', name: 'location', widget: 'string', required: false, hint: 'Behövs ej' }
      - { label: 'Fb-länk', name: 'facebookLink', widget: 'string', required: false, hint: 'Länk till event på facebook. Behövs ej' }
  - name: 'pages'
    label: 'Sidor'
    folder: 'src/pages'
    create: false
    fields:
      - { label: 'Undertext', name: 'undertext', widget: 'markdown', hint: 'Den första texten under "Ung i världen"' }
