backend:
  name: git-gateway
  branch: main

media_folder: 'src/assets/images'
#public_folder: '/_astro'
public_folder: '~/assets/images'

site_url: https://ungivarlden.netlify.app
logo_url: https://i.imgur.com/Z7DSFCm.png
locale: 'sv'

collections:
  - name: 'post'
    label: 'Events'
    folder: 'src/content/post'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Kort beskrivning', name: 'excerpt', widget: 'string' }
      #- { label: 'Category', name: 'category', widget: 'string' }
      - {
          label: 'Tags',
          name: 'tags',
          widget: 'list',
          allow_add: true,
          allow_delete: true,
          collapsed: true,
          field: { label: 'Tag', name: 'tag', widget: 'string' },
        }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Datum (start-datum)', name: 'publishDate', widget: 'datetime', required: true }
      - { label: 'Slutdatum', name: 'endDate', widget: 'datetime', default: , required: false, hint: 'Rör inte detta fältet alls om du ej vill ha ett slutdatum!!' }
      #- { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Plats', name: 'location', widget: 'string', required: false, hint: 'Behövs ej' }
      - { label: 'Fb-länk', name: 'facebookLink', widget: 'string', required: false, hint: 'Länk till event på facebook. Behövs ej' }
      - { label: 'Avpublicera', name: 'draft', widget: 'boolean', hint: 'Klicka i för att avpublicera från hemsidan (går fortf att redigera här)'}
      - { label: 'Content', name: 'body', widget: 'markdown', hint: 'Vidare information fritext'}
  - name: 'pages'
    label: 'Hem'
    folder: 'src/pages'
    create: false
    fields:
      - { label: 'Titel', name: 'title', widget: string }
      - { label: 'Undertitel', name: 'undertext', widget: 'text', hint: 'Den första texten under titeln' }
      - label: 'Cover Image'
        name: 'heroImage'
        widget: 'object'
        fields:
          - { label: 'Bild', name: 'src', widget: 'image' }
          - { label: 'Alternativ text', name: 'alt', widget: 'string' }
      - label: 'Intro bild'
        name: 'introImage'
        widget: 'object'
        fields:
          - { label: 'Bild', name: 'src', widget: 'image' }
          - { label: 'Alternativ text', name: 'alt', widget: 'string' }
      - { label: 'Vidare Intro kort om oss - Titel', name: 'introTitle', widget: 'string' }
      - { label: 'Vidare Intro kort om oss - text', name: 'introText', widget: 'text' }
      - { label: 'Värderingar - tagline (lilla över titel)', name: valuesTagline, widget: string, required: false }
      - { label: 'Värderingar - Titel', name: valuesTitle, widget: string }
      - { label: 'Värderingar - undertitel', name: valuesSubtitle, widget: string, required: false }
      - { label: 'Värderingar - läs mer', name: valuesReadMore, widget: string, required: false }
      - label: 'Värderingsar'
        name: 'values'
        widget: 'list'
        collapsed: true
        allow_add: true
        allow_remove: true
        fields:
          - { label: 'Bild', name: 'image', widget: 'object', fields: [ {label: 'Bild', name: 'src', widget: 'image'}, {label: 'Alternativ text', name: alt, widget: string } ] }
          - { label: 'Rubrik', name: 'title', widget: 'string' }
      - { label: 'Text angående kommande event', name: 'eventText', widget: 'string' }
  - name: 'värdegrund'
    label: 'Värdegrund'
    folder: 'src/pages/värdegrund'
    create: false
    fields:
      - { label: 'Tagline (lilla över titeln)', name: 'tagline', widget: 'string', required: false }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Undertitel', name: 'subtitle', widget: 'string', required: false }
      - label: 'Cover Image'
        name: 'heroImage'
        widget: 'object'
        fields:
          - { label: 'Bild', name: 'src', widget: 'image' }
          - { label: 'Alternativ text', name: 'alt', widget: 'string' }
      - { label: 'Värderingar tagline (lilla över titel)', name: valuesTagline, widget: string, required: false }
      - { label: 'Värderingar titel', name: valuesTitle, widget: string }
      - { label: 'Värderingar undertitel', name: valuesSubtitle, widget: string, required: false }
      - label: 'Värderingsar'
        name: 'values'
        widget: 'list'
        collapsed: true
        allow_add: true
        allow_remove: true
        fields:
          - { label: 'Bild', name: 'image', widget: 'object', fields: [ {label: 'Bild', name: 'src', widget: 'image'}, {label: 'Alternativ text', name: alt, widget: string } ] }
          - { label: 'Rubrik', name: 'title', widget: 'string' }
          - { label: 'Beskrivning', name: 'description', widget: 'string' }
      #- { label: 'Fritext', name: body, widget: 'markdown' }
  - name: 'om'
    label: 'Om oss'
    folder: 'src/pages/om'
    create: false
    fields:
      - { label: 'Tagline (det lilla över titel)', name: 'tagline', widget: 'string', required: false }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Undertitel', name: 'subtitle', widget: 'string', required: false }
      - label: 'Cover Image'
        name: 'heroImage'
        widget: 'object'
        fields:
          - { label: 'Bild', name: 'src', widget: 'image' }
          - { label: 'Alternativ text', name: 'alt', widget: 'string' }
      #- label: 'Värderingsar'
      #  name: 'values'
      #  widget: 'list'
      #  collapsed: true
      #  allow_add: true
      #  allow_remove: true
      #  fields:
      #    - { label: 'Bild', name: 'image', widget: 'object', fields: [ {label: 'Bild', name: 'src', widget: 'image'} ] }
      #    - { label: 'Rubrik', name: 'title', widget: 'string' }
      #    - { label: 'Beskrivning', name: 'description', widget: 'string' }
      - { label: 'Titel kontakt-ruta', name: 'contactTitle', widget: 'string', required: false }
      - { label: 'Undertitel kontakt-ruta', name: 'contactSubtitle', widget: 'string', required: false }
      - { label: 'Fritext', name: body, widget: 'markdown' }
  - name: 'kontakt'
    label: 'Kontakt'
    folder: 'src/pages/kontakt'
    create: false
    fields:
      - { label: 'Tagline (det översta lilla blå)', name: 'tagline', widget: 'string', required: false }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Undertitel', name: 'subtitle', widget: 'string', required: false }
      - label: 'Cover Image'
        name: 'heroImage'
        widget: 'object'
        fields:
          - { label: 'Bild', name: 'src', widget: 'image' }
          - { label: 'Alternativ text', name: 'alt', widget: 'string' }
      - { label: 'Titel meddelande-ruta', name: 'messageBoxTitle', widget: 'string', required: false }
      - { label: 'Undertitel meddelande-ruta', name: 'messageBoxSubtitle', widget: 'string', required: false }
      - { label: 'När formuläret har skickats text', name: 'messageBoxSubmitMessage', widget: 'string' }
      - { label: 'Titel kontaktuppgifter', name: 'individualTitle', widget: 'string', required: false }
      - { label: 'Undertitel kontaktuppgifter', name: 'individualSubtitle', widget: 'string', required: false }
      - label: 'Kontaktuppgifter'
        name: 'individualContacts'
        widget: 'list'
        collapsed: true
        allow_add: true
        allow_remove: true
        fields:
          - { label: 'Namn', name: 'title', widget: 'string' }
          - { label: 'Beskrivning', name: 'description', widget: 'string', required: false }
          - { label: 'Mail', name: 'mail', widget: 'string', required: false }
          - { label: 'LinkedIn', name: 'linkedIn', widget: 'string', required: false, hint: "hela url:en till er profil" }
          - { label: 'Bild', name: 'image', widget: 'object', fields: [ { label: 'Bild', name: src, widget: image, required: false }]}
          - { label: Ikon, name: icon, widget: string, hint: 'börjar med tabler: (alla ikoner finns på https://tabler.io/icons)', default: "tabler:user", required: false}
  - name: 'bli-medlem'
    label: 'Bli medlem'
    folder: 'src/pages/bli-medlem'
    create: false
    fields:
      - { label: 'Tagline (det översta lilla blå)', name: 'tagline', widget: 'string', required: false }
      - { label: 'Huvuditel', name: 'title', widget: 'string', required: false }
      - { label: 'Text under titel', name: 'subtitle', widget: 'string', required: false }
      - label: 'Cover Image'
        name: 'heroImage'
        widget: 'object'
        fields:
          - { label: 'Bild', name: 'src', widget: 'image' }
          - { label: 'Alternativ text', name: 'alt', widget: 'string' }
      - { label: 'Titel formulär', name: 'formTitle', widget: 'string', required: false }
      - { label: 'Text under titel formulär', name: 'formSubtitle', widget: 'string', required: false }
      - { label: 'Kryssrutan text', name: 'checkBoxText', widget: 'string', required: false, hint: 'Lämna blank för att inte ha en kryssruta' }
      - { label: 'Text på knapp', name: 'buttonText', widget: 'string', required: false }
      - { label: 'När formuläret har skickats text', name: 'submitText', widget: 'string' }